<?php

/**
 * BaseMarkaProductImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $filename
 * @property integer $product_id
 * @property boolean $is_primary
 * @property MarkaProduct $Product
 * 
 * @method string            getFilename()   Returns the current record's "filename" value
 * @method integer           getProductId()  Returns the current record's "product_id" value
 * @method boolean           getIsPrimary()  Returns the current record's "is_primary" value
 * @method MarkaProduct      getProduct()    Returns the current record's "Product" value
 * @method MarkaProductImage setFilename()   Sets the current record's "filename" value
 * @method MarkaProductImage setProductId()  Sets the current record's "product_id" value
 * @method MarkaProductImage setIsPrimary()  Sets the current record's "is_primary" value
 * @method MarkaProductImage setProduct()    Sets the current record's "Product" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMarkaProductImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('marka_product_image');
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_primary', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MarkaProduct as Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}