<?php

/**
 * BaseMarkaEventImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $filename
 * @property integer $event_id
 * @property MarkaEvent $Event
 * 
 * @method string            getFilename()   Returns the current record's "filename" value
 * @method integer           getEventId()  Returns the current record's "event_id" value
 * @method MarkaEvent      getEvent()    Returns the current record's "Event" value
 * @method MarkaEventImage setFilename()   Sets the current record's "filename" value
 * @method MarkaEventImage setEventId()  Sets the current record's "event_id" value
 * @method MarkaEventImage setEvent()    Sets the current record's "Event" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMarkaEventImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('marka_event_image');
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MarkaEvent as Event', array(
             'local' => 'event_id',
             'foreign' => 'id'));
    }
}