<?php

/**
 * BaseMarkaHomeSlider
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $filename
 * @property string $caption
 * @property integer $priority
 * 
 * @method string          getFilename() Returns the current record's "filename" value
 * @method string          getCaption()  Returns the current record's "caption" value
 * @method integer         getPriority() Returns the current record's "priority" value
 * @method MarkaHomeSlider setFilename() Sets the current record's "filename" value
 * @method MarkaHomeSlider setCaption()  Sets the current record's "caption" value
 * @method MarkaHomeSlider setPriority() Sets the current record's "priority" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMarkaHomeSlider extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('marka_home_slider');
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('caption', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('priority', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}