<?php

/**
 * BaseMarkaOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $pending
 * @property boolean $shipped
 * @property integer $customer_id
 * @property MarkaCustomer $Customer
 * @property Doctrine_Collection $MarkaOrderDetails
 * 
 * @method boolean             getPending()           Returns the current record's "pending" value
 * @method boolean             getShipped()           Returns the current record's "shipped" value
 * @method integer             getCustomerId()        Returns the current record's "customer_id" value
 * @method MarkaCustomer       getCustomer()          Returns the current record's "Customer" value
 * @method Doctrine_Collection getMarkaOrderDetails() Returns the current record's "MarkaOrderDetails" collection
 * @method MarkaOrder          setPending()           Sets the current record's "pending" value
 * @method MarkaOrder          setShipped()           Sets the current record's "shipped" value
 * @method MarkaOrder          setCustomerId()        Sets the current record's "customer_id" value
 * @method MarkaOrder          setCustomer()          Sets the current record's "Customer" value
 * @method MarkaOrder          setMarkaOrderDetails() Sets the current record's "MarkaOrderDetails" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMarkaOrder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('marka_order');
        $this->hasColumn('pending', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('shipped', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('customer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MarkaCustomer as Customer', array(
             'local' => 'customer_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('MarkaOrderDetails', array(
             'local' => 'id',
             'foreign' => 'order_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}