<?php

/**
 * BaseMarkaOrderDetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $order_id
 * @property integer $product_id
 * @property integer $quantity
 * @property integer $cadprice
 * @property MarkaOrder $Order
 * @property MarkaProduct $Product
 * 
 * @method integer           getOrderId()    Returns the current record's "order_id" value
 * @method integer           getProductId()  Returns the current record's "product_id" value
 * @method integer           getQuantity()   Returns the current record's "quantity" value
 * @method integer           getCadprice()   Returns the current record's "cadprice" value
 * @method MarkaOrder        getOrder()      Returns the current record's "Order" value
 * @method MarkaProduct      getProduct()    Returns the current record's "Product" value
 * @method MarkaOrderDetails setOrderId()    Sets the current record's "order_id" value
 * @method MarkaOrderDetails setProductId()  Sets the current record's "product_id" value
 * @method MarkaOrderDetails setQuantity()   Sets the current record's "quantity" value
 * @method MarkaOrderDetails setCadprice()   Sets the current record's "cadprice" value
 * @method MarkaOrderDetails setOrder()      Sets the current record's "Order" value
 * @method MarkaOrderDetails setProduct()    Sets the current record's "Product" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMarkaOrderDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('marka_order_details');
        $this->hasColumn('order_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('quantity', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('cadprice', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MarkaOrder as Order', array(
             'local' => 'order_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('MarkaProduct as Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}