<?php

/**
 * BaseMarkaColorScheme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $slug
 * @property string $description
 * @property string $hexcolor1
 * @property string $hexcolor2
 * @property string $hexcolor3
 * @property Doctrine_Collection $Products
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getSlug()        Returns the current record's "slug" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getHexcolor1()   Returns the current record's "hexcolor1" value
 * @method string              getHexcolor2()   Returns the current record's "hexcolor2" value
 * @method string              getHexcolor3()   Returns the current record's "hexcolor3" value
 * @method Doctrine_Collection getProducts()    Returns the current record's "Products" collection
 * @method MarkaColorScheme    setName()        Sets the current record's "name" value
 * @method MarkaColorScheme    setSlug()        Sets the current record's "slug" value
 * @method MarkaColorScheme    setDescription() Sets the current record's "description" value
 * @method MarkaColorScheme    setHexcolor1()   Sets the current record's "hexcolor1" value
 * @method MarkaColorScheme    setHexcolor2()   Sets the current record's "hexcolor2" value
 * @method MarkaColorScheme    setHexcolor3()   Sets the current record's "hexcolor3" value
 * @method MarkaColorScheme    setProducts()    Sets the current record's "Products" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMarkaColorScheme extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('marka_color_scheme');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('hexcolor1', 'string', 7, array(
             'type' => 'string',
             'length' => 7,
             ));
        $this->hasColumn('hexcolor2', 'string', 7, array(
             'type' => 'string',
             'length' => 7,
             ));
        $this->hasColumn('hexcolor3', 'string', 7, array(
             'type' => 'string',
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MarkaProduct as Products', array(
             'local' => 'id',
             'foreign' => 'colorscheme_id'));
    }
}