<?php

/**
 * BaseMarkaEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $place
 * @property date $date
 * @property boolean $is_upcoming
 * @property string $description
 * @property string $short
 * @property Doctrine_Collection $Images
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getPlace()       Returns the current record's "place" value
 * @method date                getDate()        Returns the current record's "date" value
 * @method boolean             getIsUpcoming()  Returns the current record's "is_upcoming" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getShort()       Returns the current record's "short" value
 * @method Doctrine_Collection getImages()      Returns the current record's "Images" collection
 * @method MarkaEvent          setName()        Sets the current record's "name" value
 * @method MarkaEvent          setPlace()       Sets the current record's "place" value
 * @method MarkaEvent          setDate()        Sets the current record's "date" value
 * @method MarkaEvent          setIsUpcoming()  Sets the current record's "is_upcoming" value
 * @method MarkaEvent          setDescription() Sets the current record's "description" value
 * @method MarkaEvent          setShort()       Sets the current record's "short" value
 * @method MarkaEvent          setImages()      Sets the current record's "Images" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMarkaEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('marka_event');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('place', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('is_upcoming', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('description', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('short', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MarkaEventImage as Images', array(
             'local' => 'id',
             'foreign' => 'event_id',
             'cascade' => array(
             0 => 'delete',
             )));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}