sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

marka_home_slider:
  class: sfDoctrineRouteCollection
  options:
    model:                MarkaHomeSlider
    module:               homeslider
    prefix_path:          /homeslider
    column:               id
    with_wildcard_routes: true

marka_customer:
  class: sfDoctrineRouteCollection
  options:
    model:                MarkaCustomer
    module:               customers
    prefix_path:          /customers
    column:               id
    with_wildcard_routes: true

marka_order:
  class: sfDoctrineRouteCollection
  options:
    model:                MarkaOrder
    module:               orders
    prefix_path:          /orders
    column:               id
    with_wildcard_routes: true

marka_product:
  class: sfDoctrineRouteCollection
  options:
    model:                MarkaProduct
    module:               product
    prefix_path:          /product
    column:               slug
    with_wildcard_routes: true

marka_event:
  class: sfDoctrineRouteCollection
  options:
    model:                MarkaEvent
    module:               event
    prefix_path:          /event
    column:               id
    with_wildcard_routes: true	


#marka_product_image_upload:
#  url:     /product/uploadimage/:slug
#  class:   sfDoctrineRoute
#  options: { model: MarkaProduct, type: object }
#  param:   { module: product, action: uploadimage }
#  requirements: { sf_method: post }

#marka_product_image_delete:
#  url:     /product/deleteimage/:slug
#  class:   sfDoctrineRoute
#  options: { model: MarkaProduct, type: object }
#  param:   { module: product, action: deleteimage }
#  requirements: { sf_method: post }
 
marka_category:
  class: sfDoctrineRouteCollection
  options:
    model:                MarkaCategory
    module:               category
    prefix_path:          /category
    column:               slug
    with_wildcard_routes: true

marka_color_scheme:
  class: sfDoctrineRouteCollection
  options:
    model:                MarkaColorScheme
    module:               colorscheme
    prefix_path:          /colorscheme
    column:               slug
    with_wildcard_routes: true
    
marka_type:
  class: sfDoctrineRouteCollection
  options:
    model:                MarkaType
    module:               type
    prefix_path:          /type
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: product, action: index }

default:
  url:   /:module/:action/*

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*
