generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MarkaProduct
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          marka_product
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        stockqty: {label: Qty }
        cadprice: {label: Price }
        is_active:
          label: Active
      list:
        display: [=name, category_id, colorscheme_id, stockqty, cadprice, is_active]
      filter:
        display: [category_id, colorscheme_id, is_active]
      form:    ~
      edit:
        display: [name, category_id, colorscheme_id, is_active, manufactured, stockqty, cadprice, is_active, description, short]
      new:
        display: [name, category_id, colorscheme_id, is_active, manufactured, stockqty, cadprice, is_active, description, short]
