generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MarkaProduct
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          marka_product
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   false
    
    config:
      actions: ~
      fields:
        name:
          help: Should pick a unique, short name (maximum length is 50).
          attributes: { maxlength: 50, size: 50 }
        stockqty:
          label: Quantity
          help: How many you have in stock
          attributes: { size: 2 }
        cadprice:
          label: Price (CAD)
          attributes: { size: 4 }
        short:
          label: Short description
          attributes: { maxlength: 100, size: 80 }
          help: Physical sizes, materials, etc.
        description:
          attributes: { rows: 13, cols: 80 }
          help: Should fill the whole textarea (maximum length is 2000 characters)!
        imagecount:
          label: Images
      list:
        display: [=name, category_id, type_id, stockqty, cadprice, featured, is_active, imagecount]
        fields:
          is_active:
            label: Active
          stockqty: {label: Qty }
          cadprice: {label: Price }
        batch_actions: { _delete: ~, _activate: ~, _deactivate: ~ }
      filter:
        display: [category_id, type_id, is_active, featured]
      form:    ~
      edit:
        display: [name, category_id, type_id, is_active, featured, stockqty, cadprice, short, description]
        fields:
          is_active:
            label: Publish?
            help: If checked, the product will go online, otherwise customers won't see it until activated.
          featured:
            label: Featured
            help: If checked, the product will be added to the featured products set.
      new:
        display: [name, category_id, type_id, stockqty, cadprice, short, description]
