<?php

/**
 * MarkaOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MarkaOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MarkaOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MarkaOrder');
    }
}