<?php

/**
 * MarkaEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MarkaEvent extends BaseMarkaEvent
{ 
  
  public function getImagecount() {
    return $this->getImages()->count();
  }
  
  public function activate() {
    $this->setIsActive(true);
    $this->save();
  }
  
  public function deactivate() {
    $this->setIsActive(false);
    $this->save();
  }
 
  public function featurize() {
    $this->setFeatured(true);
    $this->save();
  }
  
  public function unfeaturize() {
    $this->setFeatured(false);
    $this->save();
  }
}
