<?php

/**
 * MarkaCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MarkaCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MarkaCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MarkaCategory');
    }
}