<?php

/**
 * MarkaCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MarkaCategory extends BaseMarkaCategory
{
  public function getCategorySlug() {
    return Utility::slugify($this->getName());
  }
  
  public function countActiveProducts()
  {
    $q = Doctrine_Query::create()
      ->from('MarkaProduct m')
      ->where('m.category_id = ?', $this->getId());
 
    return Doctrine_Core::getTable('MarkaProduct')->countActiveProducts($q);
  }
  
  public function getActiveProducts()
  {
    $q = Doctrine_Query::create()
      ->from('MarkaProduct m')
      ->where('m.category_id = ?', $this->getId());
 
    return Doctrine_Core::getTable('MarkaProduct')->getActiveProducts($q);
  }
  
}
