<?php

/**
 * MarkaProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MarkaProduct extends BaseMarkaProduct
{
  public function getColorSchemeSlug() {
    return $this->getColorScheme()->getSlug();
  }
  
  public function getCategorySlug() {
    return $this->getCategory()->getSlug();
  }
  
  public function getPrimaryImage() {
    return Doctrine_Core::getTable('MarkaProductImage')->getPrimaryImageOf($this->getId());
  }
  
  public function getAdditionalImages() {
    return Doctrine_Core::getTable('MarkaProductImage')->getAdditionalImagesOf($this->getId());
  }
  
  public function getImage() {
    $image = sfConfig::get('app_product_image_dir').$this->getToken().'.'.sfConfig::get('app_image_ext');
    return ( file_exists( $image ) )
      ? DIRECTORY_SEPARATOR.$image
      : "http://dummyimage.com/200x120/46475c/dadbe3.png&text=No Image";
  }
 
}
