<?php

/**
 * MarkaCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MarkaCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MarkaCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MarkaCategory');
    }
    
    public function getActiveCategories()
    {
      return $this->createQuery('c')->innerJoin('c.Products p')->where('p.is_active = true')->execute();
    }
    
    public function getChoices()
    {
      $categories = $this->getNotEmptyCategories();
      $ret = array();
      foreach ($categories as $cat) {
        $ret[$cat->getSlug()] = $cat->getName();
      }
      return $ret;
    }
    
    /*
    public function getRandomLimitedCategories($limit)
    {
      return $this->createQuery('c')
              ->select('*,RANDOM() AS rand')
              ->orderBy('rand')
              ->limit($limit)
              ->execute();
    }*/
    
}