<?php

/**
 * MarkaColorSchemeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MarkaColorSchemeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MarkaColorSchemeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MarkaColorScheme');
    }
    
    public function getActiveColorSchemes()
    {
      return $this->createQuery('c')->innerJoin('c.Products p')->where('p.is_active = true')->execute();
    }
    
    public function getChoices()
    {
      $colorschemes = $this->getActiveColorSchemes();
      $ret = array();
      foreach ($colorschemes as $cs) {
        $ret[$cs->getSlug()] = $cs->getName();
      }
      return $ret;
    }
}