<?php

/**
 * MarkaHomeSliderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MarkaHomeSliderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MarkaHomeSliderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MarkaHomeSlider');
    }
    
    public function getSlides()
    {
      return $this->createQuery('h')->orderBy('priority ASC')->execute();
    }
}