<?php

/**
 * MarkaType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MarkaType extends BaseMarkaType
{
  public function getCategories()
  {
    $q = Doctrine_Query::create()
      ->select('c.*')
      ->from('MarkaCategory c')
      ->innerJoin('c.Products p')
      ->where('p.type_id = ?', $this->getId());
 
    return $q->execute();
  }
  
  public function getActiveCategories()
  {
    $q = Doctrine_Query::create()
      ->select('c.*')
      ->from('MarkaCategory c')
      ->innerJoin('c.Products p')
      ->where('p.type_id = ?', $this->getId())
      ->andWhere('p.is_active = true');
 
    return $q->execute();
  }
  
  public function save(Doctrine_Connection $conn = null)
  {
    $this->setSlug( Utility::slugify($this->getName()) );
    return parent::save($conn);
  }
  
  public function getProductCount() {
    return $this->getProducts()->count();
  }
}
