<?php

/**
 * MarkaProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MarkaProduct extends BaseMarkaProduct
{
  
  public function save(Doctrine_Connection $conn = null)
  {
    if ( $this->isNew() ) {
      $this->setSlug( Utility::slugify($this->getName()) );
      $this->setToken(sha1($this->getSlug()));
    }
    $ret = parent::save($conn);
  }
  
  public function getColorSchemeSlug() {
    return $this->getColorScheme()->getSlug();
  }
  
  public function getCategorySlug() {
    return $this->getCategory()->getSlug();
  }
  
  public function getImagecount() {
    return $this->getImages()->count();
  }
  
  public function activate() {
    $this->setIsActive(true);
    $this->save();
  }
  
  public function deactivate() {
    $this->setIsActive(false);
    $this->save();
  }
 
}
