<?php

/**
 * MarkaOrderDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MarkaOrderDetailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MarkaOrderDetailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MarkaOrderDetails');
    }
}