<?php

/**
 * MarkaTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MarkaTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MarkaTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MarkaType');
    }
    
    public function getActiveTypes()
    {
      return $this->createQuery('c')->innerJoin('c.Products p')->where('p.is_active = true')->execute();
    }
    
    public function getChoices()
    {
      $types = $this->getActiveTypes();
      $ret = array();
      foreach ($types as $t) {
        $ret[$t->getSlug()] = $t->getName();
      }
      return $ret;
    }
}