<?php

/**
 * MarkaCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MarkaCategory extends BaseMarkaCategory
{
  public function save(Doctrine_Connection $conn = null)
  {
    $this->setSlug( Utility::slugify($this->getName()) );
    $ret = parent::save($conn);
    
    if ( $this->hasIcon() ) {
      $image_file = sfConfig::get('sf_web_dir').$this->getIconPath();
      $img = new sfImage($image_file);
      $sizes = explode('x',sfConfig::get('app_category_icon_size'));
      $img->resize($sizes[0],$sizes[1])->save();
    } else {
      $this->setIcon("");
    }    
    return $ret;
  }
  
  public function getIconpath() {
    return sfConfig::get('app_category_icon_dir') . $this->getIcon();
  }
  
  public function hasIcon() {
    $image_file = sfConfig::get('sf_web_dir').$this->getIconPath();
    return is_file($image_file);
  }
  
  public function getProductCount() {
    return $this->getProducts()->count();
  }
  
  
  /*
  public function countActiveProducts()
  {
    $q = Doctrine_Query::create()
      ->from('MarkaProduct m')
      ->where('m.category_id = ?', $this->getId());
 
    return Doctrine_Core::getTable('MarkaProduct')->countActiveProducts($q);
  }
  
  public function getActiveProducts()
  {
    $q = Doctrine_Query::create()
      ->from('MarkaProduct m')
      ->where('m.category_id = ?', $this->getId());
 
    return Doctrine_Core::getTable('MarkaProduct')->getActiveProducts($q);
  }*/
  
}
