<?php

/**
 * MarkaProductImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MarkaProductImage extends BaseMarkaProductImage
{
  public function getImagepath() {
    return sfConfig::get('app_product_image_dir') . $this->getFilename();
  }  
}
