<?php

/**
 * MarkaEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MarkaEvent extends BaseMarkaEvent
{ 
  
  public function getImagecount() {
    return $this->getImages()->count();
  }
  
  public function markAsPastEvent() {
    $this->setIsUpcoming(false);
    $this->save();
  }
  
  public function markAsUpcomingEvent() {
    $this->setIsUpcoming(true);
    $this->save();
  }
  
}
