<?php

/**
 * MarkaCustomerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MarkaCustomerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MarkaCustomerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MarkaCustomer');
    }
}