<?php

/**
 * MarkaColorScheme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MarkaColorScheme extends BaseMarkaColorScheme
{

  public function getCategories()
  {
    $q = Doctrine_Query::create()
      ->select('c.*')
      ->from('MarkaCategory c')
      ->innerJoin('c.Products p')
      ->where('p.colorscheme_id = ?', $this->getId())
      ->andWhere('p.is_active = true');
 
    return $q->execute();
  }
  
}
