<?php

/**
 * MarkaProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MarkaProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MarkaProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MarkaProduct');
    }
    
    
  public function retrieveActiveProduct(Doctrine_Query $q)
  {
    return $this->filterActiveProducts($q)->fetchOne();
  }
 
  public function getActiveProducts(Doctrine_Query $q = null)
  {
    return $this->filterActiveProducts($q)->execute();
  }
 
  public function countActiveProducts(Doctrine_Query $q = null)
  {
    return $this->filterActiveProducts($q)->count();
  }
 
  public function filterActiveProducts(Doctrine_Query $q = null)
  {
    if (is_null($q))
    {
      $q = Doctrine_Query::create()
        ->from('MarkaProduct m');
    }
 
    $alias = $q->getRootAlias();
 
    $q->andWhere($alias . '.is_active = true')
      ->addOrderBy($alias . '.created_at DESC');
 
    return $q;
  }
}