<?php

/**
 * MarkaProductImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MarkaEventImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MarkaProductImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MarkaEventImage');
    }
}