# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# Showcase of structure

world_product:
  url:     /world-of-marka/:colorscheme_slug/:category_slug/:slug
  class:   sfDoctrineRoute
  options: { model: MarkaProduct, type: object }
  param:   { module: world, action: productView }
  requirements:
    token: ([a-fA-F\d]){32}
    sf_method: [get]

world_category:
  url:     /world-of-marka/:colorscheme_slug/:category_slug
  class:   sfRequestRoute
  param:   { module: world, action: categoryView }
  requirements:
    sf_method: [get]

world_colorscheme:
  url:     /world-of-marka/:slug
  class:   sfDoctrineRoute
  options: { model: MarkaColorScheme, type: object }
  param:   { module: world, action: colorschemeView }
  requirements:
    id: \d+
    sf_method: [get]

# Shopping Cart related routes
cart_show:
  url:   /cart
  param: { module: cart, action: show }
  requirements:
    sf_method: [get]
    
cart_push:
  url:   /cart/push/:token
  param: { module: cart, action: push }
  requirements:
    token: ([a-fA-F\d]){32}
    sf_method: [get]
    
cart_pop:
  url:   /cart/pop/:token
  param: { module: cart, action: pop }
  requirements:
    token: ([a-fA-F\d]){32}
    sf_method: [get]
    
cart_clear:
  url:   /cart/clear
  param: { module: cart, action: clear }
  requirements:
    sf_method: [get]
    

store:
  url:     /store
  param:   { module: store, action: display }
  

about:
  url:     /about-marka
  param:   { module: content, action: about }

contact:
  url:   /contact
  param: { module: content, action: contact }

home:
  url:   /
  param: { module: content, action: home }