# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# Showcase of structure
world_product:
  url:     /world-of-marka/:category_slug/:type_slug/:slug
  class:   sfDoctrineRoute
  options: { model: MarkaProduct, type: object }
  param:   { module: content, action: productView }
  requirements:
    token: ([a-fA-F\d]){32}
    sf_method: [get]

event:
  url:     /event/:id
  class:   sfDoctrineRoute
  options: { model: MarkaEvent, type: object }
  param:   { module: content, action: eventView }
  requirements:
    token: ([a-fA-F\d]){32}
    sf_method: [get]

event_full:
  url:     /event
  param:   { module: content, action: eventbrowserView }
  requirements:
    sf_method: [get]

world:
  url:     /world-of-marka
  param:   { module: content, action: browserView }
  requirements:
    sf_method: [get]
    
world_fetch:
  url:    /fetch/:category_slug/:type_slug
  class:  sfRequestRoute
  param:  { module: content, action: fetch }

world_fetch_featured:
  url:    /fetch
  class:  sfRequestRoute
  param:  { module: content, action: fetchFeatured }
  


# Shopping Cart related routes
cart_show:
  url:   /cart
  param: { module: cart, action: show }
  requirements:
    sf_method: [get]
    
cart_push:
  url:   /cart/push/:token
  param: { module: cart, action: push }
  requirements:
    token: ([a-fA-F\d]){32}
    sf_method: [get]
    
cart_pop:
  url:   /cart/pop/:token
  param: { module: cart, action: pop }
  requirements:
    token: ([a-fA-F\d]){32}
    sf_method: [get]
    
cart_clear:
  url:   /cart/clear
  param: { module: cart, action: clear }
  requirements:
    sf_method: [get]
    
    
# Static routes

about:
  url:     /about
  param:   { module: content, action: about }

contact:
  url:   /contact
  param: { module: content, action: contact }
  
contact-submit:
  url:   /contact/submit
  param: { module: content, action: contactSubmit }

home:
  url:   /
  param: { module: content, action: home }