# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# Online Store related routes

showcase_product:
  url:     /:colorscheme_slug/:category_slug/:slug
  class:   sfDoctrineRoute
  options: { model: MarkaProduct, type: object }
  param:   { module: showcase, action: productView }
  requirements:
    token: ([a-fA-F\d]){32}
    sf_method: [get]

showcase_category:
  url:     /:colorscheme_slug/:category_slug
  class:   sfRequestRoute
  param:   { module: showcase, action: categoryView }
  requirements:
    sf_method: [get]

showcase_colorscheme:
  url:     /:slug
  class:   sfDoctrineRoute
  options: { model: MarkaColorScheme, type: object }
  param:   { module: showcase, action: colorschemeView }
  requirements:
    id: \d+
    sf_method: [get]

store:
  url:     /store
  param:   { module: store, action: display }
  
# Shopping Cart related routes

cart_show:
  url:   /cart
  param: { module: cart, action: show }
  requirements:
    sf_method: [get]
    
cart_push:
  url:   /cart/push/:token
  param: { module: cart, action: push }
  requirements:
    token: ([a-fA-F\d]){32}
    sf_method: [get]
    
cart_pop:
  url:   /cart/pop/:token
  param: { module: cart, action: pop }
  requirements:
    token: ([a-fA-F\d]){32}
    sf_method: [get]
    
cart_clear:
  url:   /cart/clear
  param: { module: cart, action: clear }
  requirements:
    sf_method: [get]
  
#Other routes  
  
about:
  url:   /about
  param: { module: content, action: about }
  
inspiration:
  url:   /inspiration
  param: { module: content, action: inspiration }

contact:
  url:   /contact
  param: { module: content, action: contact }
  
world:
  url:   /world-of-marka
  param: { module: concept, action: index }

home:
  url:   /
  param: { module: content, action: home }