# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  stylesheets:
    - http://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin
    - http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,700
    - reset.css
    - grid.css
    - marka.css
    
  javascripts:
    - libs/jquery-1.7.1.min.js
    - plugins.js
    
  has_layout:     true
  layout:         layout
