generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MarkaEvent
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          marka_event
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   false
    
    config:
      actions: ~
      fields:
        name:
          help: The event.
          attributes: { maxlength: 50, size: 50 }
        place:
          label: Place
          help: The place of the event.
          attributes: { maxlength: 50, size: 50 }
        short:
          label: Short description
          attributes: { maxlength: 100, size: 80 }
          help: Short description
        date:
          label: Date
          attributes: { }
          help: The date of the event M/D/Y
        is_upcoming:
          label: upcoming
          attributes: {}
          help: yes or no
        description:
          attributes: { rows: 13, cols: 80 }
          help: Should fill the whole textarea (maximum length is 2000 characters)!
        imagecount:
          label: Images
      list:
        display: [=name, imagecount]
        fields:
          is_active:
            label: Active
        batch_actions: { _delete: ~, _batchMarkAsPastEvent~ , _batchMarkAsUpcomingEvent~}
      filter:
        display: [date, is_upcoming]
      form:    ~
      edit:
        display: [name, place, date, is_upcoming, short, description]
      new:
        display: [name, place, date, is_upcoming, short, description]
