generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MarkaEvent
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          marka_event
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   false
    
    config:
      actions: ~
      fields:
        name:
          help: Event.
          attributes: { maxlength: 50, size: 50 }
        place:
          help: Place.
          attributes: { maxlength: 50, size: 50 }
        short:
          label: Short description
          attributes: { maxlength: 100, size: 80 }
          help: info
        description:
          attributes: { rows: 13, cols: 80 }
          help: Should fill the whole textarea (maximum length is 2000 characters)!
        imagecount:
          label: Images
      list:
        display: [=name, imagecount]
        fields:
          is_active:
            label: Active
        batch_actions: { _delete: ~}
      form:    ~
      edit:
        display: [name, short, description]
      new:
        display: [name, short, description]
