generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MarkaCategory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          marka_category
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields: 
        name: 
          attributes: { size: 70, maxlength: 100 } 
          help: Should be no longer than 20 characters (maximum is 100 characters)
        description: 
          attributes: { size: 70, maxlength: 255 } 
          help: Maximum length is 255 characters!
      list:
        display: [=name, products]
        batch_actions: {}
      filter:
        class: false
      form:    ~
      edit:
        display: [name, description]
      new:
        display: [name, description]
