generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MarkaCategory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          marka_category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name, description, products]
        batch_actions: {}
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
