# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  
  slider_image_dir: /app/homeslider/
  slider_image_size: 1024x768
  
  product_image_dir: /app/product/
  product_image_size: 440x440
  
  product_image_thumbnail_dir: /app/product/thumbs/
  product_image_thumbnail_size: 100x100
  
  product_image_medium_dir: /app/product/medium/
  product_image_medium_size: 143x143
  
  featured_display_count: 8
    
  sfImageTransformPlugin:
    default_adapter: GD # GD or ImageMagick
    default_image:
      mime_type: image/png
      filename: Untitled.png
    mime_type:
      auto_detect: true
      library: gd_mime_type #  gd_mime_type (GD), Fileinfo (PECL), MIME_Type (PEAR)
  