# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  
  slider_image_dir: /app/homeslider/
  slider_image_size: 1296x864
  
  product_image_dir: /app/product/
  product_image_size: 575x383
  
  product_image_thumbnail_dir: /app/product/thumbs/
  product_image_thumbnail_size: 140x93
  
  product_image_medium_dir: /app/product/medium/
  product_image_medium_size: 201x134
  
  event_image_dir: /app/product/
  event_image_size: 575x383
  
  event_image_thumbnail_dir: /app/product/thumbs/
  event_image_thumbnail_size: 140x93
  
  event_image_medium_dir: /app/product/medium/
  event_image_medium_size: 201x134
  
  featured_display_count: 8
    
  sfImageTransformPlugin:
    default_adapter: GD # GD or ImageMagick
    default_image:
      mime_type: image/png
      filename: Untitled.png
    mime_type:
      auto_detect: true
      library: gd_mime_type #  gd_mime_type (GD), Fileinfo (PECL), MIME_Type (PEAR)
  