MarkaCategory:
  columns:
    name: { type: string(100), notnull: true, unique: true }
    slug: { type: string(100), notnull: true, unique: true }
    
MarkaType:
  columns:
    name: { type: string(100), notnull: true, unique: true }
    slug: { type: string(100), notnull: true, unique: true }
   
MarkaProduct:
  actAs: 
    Timestampable:
      created:
        name: created_at
        type: timestamp
      updated:
        disabled: true
        
  columns:
    name: { type: string(50), notnull: true, unique: true }
    slug: { type: string(50), notnull: true, unique: true }
    category_id:  { type: integer, notnull: true }
    type_id:  { type: integer, notnull: true }
    manufactured: { type: date }
    token:     { type: string(255), notnull: true, unique: true }
    stockqty:  { type: integer, notnull: true, default: 1 }
    cadprice:  { type: double, notnull: true }
    is_active: { type: boolean, notnull: true, default: 0 }
    featured:  { type: boolean, notnull: true, default: 0 }
    description: { type: string(2000) }
    short: { type: string(100) }
    
  relations:
    Category: 
      class: MarkaCategory
      onDelete: RESTRICT
      local: category_id
      foreign: id
      foreignAlias: Products
    Type: 
      class: MarkaType
      onDelete: RESTRICT
      local: type_id
      foreign: id
      foreignAlias: Products
    Images:
      type: many
      class: MarkaProductImage
      local: id
      foreign: product_id
      cascade: [delete]
      foreignAlias: Product

MarkaProductImage:
  columns:
    filename: { type: string(255) }
    product_id: { type: integer }
        
MarkaHomeSlider:
  columns:
    filename: { type: string(255) }
    caption:  { type: string(100), notnull: true }
    priority: { type: integer, notnull: true, default: 1 }