homeSuccess:
  stylesheets: 
    - estro.min.css
  javascripts: 
    - libs/estro-slider.min.js
    
productViewSuccess:
  javascripts: [plugins/jquery.galleriffic.js, plugins/jquery.opacityrollover.js]
  
fetchSuccess:
  has_layout: false